import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/context/SessionProviders/SessionProviders";
import Navbar from "@/components/Nabvar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
